#ifndef BANJO_KAZOOIE_CORE2_STATICCAMERA_H
#define BANJO_KAZOOIE_CORE2_STATICCAMERA_H

enum static_camera_id_s {
    MM_ORANGE_PAD_JIGGY_SPAWN_TOP = 0xE,
    MM_ORANGE_PAD_JIGGY_SPAWN_LEFT = 0xF,
    MM_ORANGE_PAD_JIGGY_SPAWN_RIGHT = 0x10
};

#endif
