#include "src/port/ShipInit.hpp"
#include "src/port/Rando/Logic/Logic.h"

using namespace Rando::Logic;

// clang-format off
static RegisterShipInitFunc initFunc([]() {
    Regions[RR_RUSTY_BUCKET_BAY] = RandoRegion{ .regionName = "Rusty Bucket Bay", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
		// TODO: Propellor needs Event for Engine Room Switches & Snorkel needs Event for Anchor Switch
			CHECK(RC_RBB_JIGGY_CRANE_CAGE, 										CAN_USE_ABILITY(ABILITY_0_BARGE) && CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_6_EGGS)),
			CHECK(RC_RBB_JIGGY_FUNNEL, 											CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_JIGGY_JINJO, 											true),
			CHECK(RC_RBB_JIGGY_PROPELLOR, 										CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER)),
			CHECK(RC_RBB_JIGGY_SNORKEL, 										CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER) && CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_JIGGY_WHISTLE, 										CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER) && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP))),
			CHECK(RC_RBB_JINJO_GREEN, 											CAN_EXTEND_JUMP_DISTANCE),
			CHECK(RC_RBB_JINJO_ORANGE, 											CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_6_EGGS)),
			CHECK(RC_RBB_JINJO_PINK, 											CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CHECK(RC_RBB_JINJO_YELLOW, 											true),
			CHECK(RC_RBB_MUMBO_TOKEN_TOXIC_WASTE_POND, 							CAN_EXTEND_JUMP_DISTANCE && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || (CAN_USE_ABILITY(ABILITY_6_EGGS) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)))),
			CHECK(RC_RBB_MUMBO_TOKEN_ON_LIFE_BOAT, 								true),
			CHECK(RC_RBB_MUMBO_TOKEN_SHIPS_PROW, 								true),
			CHECK(RC_RBB_MUMBO_TOKEN_UNDER_CHOMPA_IN_WITCH_SWITCH_TOWER, 		CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_MUMBO_TOKEN_TOP_OF_SHIPS_CHIMNEY, 						CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
			CHECK(RC_RBB_MUMBO_TOKEN_FRONT_OF_CHOMPA_LEFT_OF_SHIP, 				CAN_USE_ABILITY(ABILITY_6_EGGS) && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_RAMP_1, 						true),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_RAMP_2, 						true),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_RAMP_3, 						true),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_RAMP_4, 						true),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_LOWER_1, 				CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_LOWER_2, 				CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_LOWER_3, 				CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_LOWER_4, 				CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_UPPER_1, 				CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_UPPER_2, 				CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_UPPER_3, 				CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_BETWEEN_SMOKE_STACKS_BRIDGE_UPPER_4, 				CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CHECK(RC_RBB_NOTE_FENCE_NEAR_YELLOW_JINJO_1, 						(CAN_USE_ABILITY(ABILITY_6_EGGS) || CAN_USE_ABILITY(ABILITY_5_CLIMB)) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_FENCE_NEAR_YELLOW_JINJO_2, 						(CAN_USE_ABILITY(ABILITY_6_EGGS) || CAN_USE_ABILITY(ABILITY_5_CLIMB)) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_FENCE_NEAR_YELLOW_JINJO_3, 						(CAN_USE_ABILITY(ABILITY_6_EGGS) || CAN_USE_ABILITY(ABILITY_5_CLIMB)) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_FENCE_NEAR_YELLOW_JINJO_4, 						(CAN_USE_ABILITY(ABILITY_6_EGGS) || CAN_USE_ABILITY(ABILITY_5_CLIMB)) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_FENCE_NEAR_YELLOW_JINJO_5, 						(CAN_USE_ABILITY(ABILITY_6_EGGS) || CAN_USE_ABILITY(ABILITY_5_CLIMB)) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_GRATE_ABOVE_PINK_JINJO_1, 						CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_GRATE_ABOVE_PINK_JINJO_2, 						CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_GRATE_ABOVE_PINK_JINJO_3, 						CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_GRATE_ABOVE_PINK_JINJO_4, 						CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
			CHECK(RC_RBB_NOTE_JIGGY_CRANE_BASE_1, 								(CAN_USE_ABILITY(ABILITY_6_EGGS) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)) || CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
			CHECK(RC_RBB_NOTE_JIGGY_CRANE_BASE_2, 								(CAN_USE_ABILITY(ABILITY_6_EGGS) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)) || CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
			CHECK(RC_RBB_NOTE_JIGGY_CRANE_BASE_3, 								(CAN_USE_ABILITY(ABILITY_6_EGGS) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)) || CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
			CHECK(RC_RBB_NOTE_RAMP_TO_SHIP_1, 									true),
			CHECK(RC_RBB_NOTE_RAMP_TO_SHIP_2, 									true),
			CHECK(RC_RBB_NOTE_RAMP_TO_SHIP_3, 									true),
			CHECK(RC_RBB_NOTE_RAMP_TO_SHIP_4, 									true),
			CHECK(RC_RBB_NOTE_RAMP_TO_SHIP_5, 									true),
			CHECK(RC_RBB_NOTE_SHIP_BOW_1, 										true),
			CHECK(RC_RBB_NOTE_SHIP_BOW_2, 										true),
			CHECK(RC_RBB_NOTE_SHIP_BOW_3, 										true),
			CHECK(RC_RBB_NOTE_SHIP_BOW_4, 										true),
			CHECK(RC_RBB_NOTE_SHIP_BOW_5, 										true),
			CHECK(RC_RBB_NOTE_SHIP_BOW_6, 										true),
			CHECK(RC_RBB_NOTE_SHIP_STERN_1, 									CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_SHIP_STERN_2, 									CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_TNT_CRANE_BASE_1, 								CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_6_EGGS)),
			CHECK(RC_RBB_NOTE_TNT_CRANE_BASE_2, 								CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_6_EGGS)),
			CHECK(RC_RBB_NOTE_TNT_CRANE_BASE_3, 								CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_5_CLIMB) && CAN_USE_ABILITY(ABILITY_6_EGGS)),
			CHECK(RC_RBB_NOTE_TOXIC_WASTE_POND_BARREL_1, 						CAN_EXTEND_JUMP_DISTANCE),
			CHECK(RC_RBB_NOTE_TOXIC_WASTE_POND_BARREL_2, 						CAN_EXTEND_JUMP_DISTANCE),
			CHECK(RC_RBB_NOTE_TOXIC_WASTE_POND_BARREL_3, 						CAN_EXTEND_JUMP_DISTANCE),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_ANCHOR,						CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_BOAT_HOUSE,					CAN_USE_ABILITY(ABILITY_F_DIVE)),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_BOSS_BOOM_BOX_ROOM,			CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_0_BARGE) && CAN_USE_ABILITY(ABILITY_5_CLIMB)),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_BUNK_CABIN,					CAN_USE_ABILITY(ABILITY_B_RATATAT_RAP)),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_CAPTAINS_CABIN,				CAN_USE_ABILITY(ABILITY_B_RATATAT_RAP)),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_ENGINE_ROOM_BEHIND_GLASS,	true),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_ENGINE_ROOM_MAIN,			CAN_ATTACK),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_KITCHEN,					true),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_NAVIGATION_ROOM,			CAN_USE_ABILITY(ABILITY_B_RATATAT_RAP)),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_SHIPPING_CONTAINER_FIRST,	CAN_USE_ABILITY(ABILITY_6_EGGS) && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_10_TALON_TROT))),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_SHIPPING_CONTAINER_SECOND,	CAN_USE_ABILITY(ABILITY_6_EGGS) && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_10_TALON_TROT))),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_SHIPPING_CONTAINER_THIRD,	CAN_USE_ABILITY(ABILITY_6_EGGS) && (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_10_TALON_TROT))),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_TNT_ROOM,					true),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_WAREHOUSE_LOWER,			true),
			CONNECTION(RR_RUSTY_BUCKET_BAY_INTERIOR_WAREHOUSE_UPPER,			CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER) && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_ANCHOR] = RandoRegion{ .regionName = "Rusty Bucket Bay Anchor Interior", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_NOTE_ANCHOR_ROOM_1,	true),
			CHECK(RC_RBB_NOTE_ANCHOR_ROOM_2,	true),
			CHECK(RC_RBB_NOTE_ANCHOR_ROOM_3,	true),
			CHECK(RC_RBB_NOTE_ANCHOR_ROOM_4,	true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, CAN_USE_ABILITY(ABILITY_F_DIVE)),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_BOAT_HOUSE] = RandoRegion{ .regionName = "Rusty Bucket Bay Boat House", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_EMPTY_HONEYCOMB_BOAT_HOUSE,	CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER) && CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, CAN_USE_ABILITY(ABILITY_F_DIVE)),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_BOSS_BOOM_BOX_ROOM] = RandoRegion{ .regionName = "Rusty Bucket Bay Boom Box Room", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_JIGGY_BOSS_BOOM_BOX,	CAN_ATTACK),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, CAN_USE_ABILITY(ABILITY_5_CLIMB)),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_BUNK_CABIN] = RandoRegion{ .regionName = "Rusty Bucket Bay Bunk Cabin", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_MUMBO_TOKEN_TOP_OF_BUNK_IN_CABIN,	CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_BUNK_CABIN_1, 				true),
			CHECK(RC_RBB_NOTE_BUNK_CABIN_2, 				true),
			CHECK(RC_RBB_NOTE_BUNK_CABIN_3, 				true),
			CHECK(RC_RBB_NOTE_BUNK_CABIN_4, 				true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_CAPTAINS_CABIN] = RandoRegion{ .regionName = "Rusty Bucket Bay Captains Cabin", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_JIGGY_CAPTAINS_CABIN, 	CAN_USE_ABILITY(ABILITY_B_RATATAT_RAP) || CAN_USE_ABILITY(ABILITY_0_BARGE) || CAN_USE_ABILITY(ABILITY_6_EGGS)),
			CHECK(RC_RBB_NOTE_CAPTAINS_CABIN_1,	true),
			CHECK(RC_RBB_NOTE_CAPTAINS_CABIN_2,	true),
			CHECK(RC_RBB_NOTE_CAPTAINS_CABIN_3,	true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_ENGINE_ROOM_BEHIND_GLASS] = RandoRegion{ .regionName = "Rusty Bucket Bay Engine Room Behind Glass", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_BEHIND_GLASS_1,	true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_BEHIND_GLASS_2,	true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_BEHIND_GLASS_3,	true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_BEHIND_GLASS_4,	true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, CAN_USE_ABILITY(ABILITY_5_CLIMB)),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_ENGINE_ROOM_MAIN] = RandoRegion{ .regionName = "Rusty Bucket Bay Engine Room Main", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_EMPTY_HONEYCOMB_ENGINE_ROOM, 				CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_JIGGY_ENGINE_ROOM, 						true),
			CHECK(RC_RBB_MUMBO_TOKEN_ENGINE_ROOM_LEFT_PIPE, 		CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_MUMBO_TOKEN_ENGINE_ROOM_RIGHT_PIPE, 		CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_MUMBO_TOKEN_ENGINE_ROOM_SPINNING_PLATFORM,	true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_LEFT_1, 					true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_LEFT_2, 					true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_LEFT_3, 					true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_LEFT_4, 					true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_MIDDLE_1, 				true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_MIDDLE_2, 				true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_MIDDLE_3, 				true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_MIDDLE_4, 				true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_RIGHT_1, 					true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_RIGHT_2, 					true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_RIGHT_3, 					true),
			CHECK(RC_RBB_NOTE_ENGINE_ROOM_RIGHT_4, 					true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, CAN_USE_ABILITY(ABILITY_5_CLIMB)),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_KITCHEN] = RandoRegion{ .regionName = "Rusty Bucket Bay Kitchen", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_MUMBO_TOKEN_INSIDE_KITCHEN,	true),
			CHECK(RC_RBB_NOTE_KITCHEN_1,				true),
			CHECK(RC_RBB_NOTE_KITCHEN_2,				true),
			CHECK(RC_RBB_NOTE_KITCHEN_3,				true),
			CHECK(RC_RBB_NOTE_KITCHEN_4,				true),
			CHECK(RC_RBB_NOTE_KITCHEN_5,				true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_NAVIGATION_ROOM] = RandoRegion{ .regionName = "Rusty Bucket Bay Navigation Room", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_MUMBO_TOKEN_INSIDE_NAVIGATION_ROOM,	true),
			CHECK(RC_RBB_NOTE_NAVIGATION_ROOM_1, 				true),
			CHECK(RC_RBB_NOTE_NAVIGATION_ROOM_2, 				true),
			CHECK(RC_RBB_NOTE_NAVIGATION_ROOM_3, 				true),
			CHECK(RC_RBB_NOTE_NAVIGATION_ROOM_4, 				true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_SHIPPING_CONTAINER_FIRST] = RandoRegion{ .regionName = "Rusty Bucket Bay Shipping Container First", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_MUMBO_TOKEN_UNDER_CHOMPA_INSIDE_FIRST_BLUE_CONTAINER, 	true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_1,				true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_2,				true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_3,				true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_4,				true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_5,				true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_6,				true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_7,				true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_FIRST_8,				true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_SHIPPING_CONTAINER_SECOND] = RandoRegion{ .regionName = "Rusty Bucket Bay Shipping Container Second", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_JINJO_BLUE, 											true),
			CHECK(RC_RBB_MUMBO_TOKEN_TOP_OF_BOX_INSIDE_SECOND_BLUE_CONTAINER,	CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, (CAN_USE_ABILITY(ABILITY_5_CLIMB) || CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP))),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_SHIPPING_CONTAINER_THIRD] = RandoRegion{ .regionName = "Rusty Bucket Bay Shipping Container Third", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_THIRD_1,	true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_THIRD_2,	true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_THIRD_3,	true),
			CHECK(RC_RBB_NOTE_SHIPPING_CONTAINER_INTERIOR_THIRD_4,	true),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_TNT_ROOM] = RandoRegion{ .regionName = "Rusty Bucket Bay TNT Room", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_MUMBO_TOKEN_TOP_OF_BOX_INSIDE_TNT_ROOM,	true),
			CHECK(RC_RBB_NOTE_TNT_ROOM_1, 							CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_TNT_ROOM_2, 							CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_TNT_ROOM_3, 							CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_TNT_ROOM_4, 							CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_TNT_ROOM_5, 							CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_WAREHOUSE_LOWER] = RandoRegion{ .regionName = "Rusty Bucket Bay Warehouse Upper", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_NOTE_WAREHOUSE_INTERIOR_1,	CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_WAREHOUSE_INTERIOR_2,	CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_WAREHOUSE_INTERIOR_3,	CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
			CHECK(RC_RBB_NOTE_WAREHOUSE_INTERIOR_4,	CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, true),
		}
	};

	Regions[RR_RUSTY_BUCKET_BAY_INTERIOR_WAREHOUSE_UPPER] = RandoRegion{ .regionName = "Rusty Bucket Bay Warehouse Upper", .levelId = LEVEL_9_RUSTY_BUCKET_BAY,
        .checks = {
			CHECK(RC_RBB_JIGGY_WAREHOUSE,	CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
		},
		.connections = {
			CONNECTION(RR_RUSTY_BUCKET_BAY, true),
		}
	};

}, {});
// clang-format on